# Generated by Django 4.2.27 on 2025-12-19 08:32

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "genre",
                    models.CharField(
                        choices=[
                            ("ACTION", "Action"),
                            ("COMEDY", "Comedy"),
                            ("DRAMA", "Drama"),
                            ("HORROR", "Horror"),
                            ("ROMANCE", "Romance"),
                            ("THRILLER", "Thriller"),
                            ("SCI-FI", "Science Fiction"),
                            ("ANIMATION", "Animation"),
                        ],
                        max_length=20,
                    ),
                ),
                ("duration", models.IntegerField(help_text="Duration in minutes")),
                ("release_date", models.DateField()),
                (
                    "poster",
                    models.ImageField(
                        blank=True, null=True, upload_to="movie_posters/"
                    ),
                ),
                ("trailer_url", models.URLField(blank=True, null=True)),
                (
                    "rating",
                    models.DecimalField(
                        decimal_places=1,
                        default=0,
                        max_digits=3,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-release_date"],
            },
        ),
        migrations.CreateModel(
            name="Theater",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("location", models.CharField(max_length=300)),
                ("capacity", models.IntegerField()),
                ("description", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Show",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("show_date", models.DateField()),
                ("show_time", models.TimeField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=8)),
                ("available_seats", models.IntegerField()),
                (
                    "movie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shows",
                        to="movies.movie",
                    ),
                ),
                (
                    "theater",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shows",
                        to="movies.theater",
                    ),
                ),
            ],
            options={
                "ordering": ["show_date", "show_time"],
                "unique_together": {("movie", "theater", "show_date", "show_time")},
            },
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "seats_booked",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("booking_date", models.DateTimeField(auto_now_add=True)),
                ("total_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "show",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to="movies.show",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-booking_date"],
            },
        ),
    ]
